/* Auto-generated by AuthSystem - 2026-03-03T05:06:34.897Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_41e38063-776',
  apiKey: 'ak_production_e5930a95735ebcd78064f9a3224f0e7f'
};
