/* Auto-generated by AuthSystem - 2025-11-14T01:46:45.639Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_41e38063-776',
  apiKey: 'ak_production_d9e9d023c004378ce2957f1240677a41'
};
